# Generated by Django 3.0 on 2019-12-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMustBuy',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Main')),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
            bases=('App.main',),
        ),
    ]
