# Generated by Django 3.0 on 2019-12-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainmustbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('main_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.Main')),
            ],
            options={
                'db_table': 'axf_shop',
            },
            bases=('App.main',),
        ),
    ]
